"""Initial migration

Revision ID: 3dee487662f7
Revises: 
Create Date: 2024-09-21 16:39:37.244554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dee487662f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudades',
    sa.Column('ciud_id', sa.Integer(), nullable=False),
    sa.Column('ciud_nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ciud_id')
    )
    op.create_table('personas',
    sa.Column('dir_tel', sa.String(), nullable=False),
    sa.Column('dir_tipo_tel', sa.String(), nullable=True),
    sa.Column('dir_nombre', sa.String(), nullable=False),
    sa.Column('dir_direccion', sa.String(), nullable=False),
    sa.Column('dir_ciud_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dir_ciud_id'], ['ciudades.ciud_id'], ),
    sa.PrimaryKeyConstraint('dir_tel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personas')
    op.drop_table('ciudades')
    # ### end Alembic commands ###
